- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Print several lines of text
  vars:
    msg: |
      Machine brand : {{ ansible_facts['system_vendor'] }}
      Machine type  : {{ ansible_facts['product_name'] }}
  debug:
    msg: "{{ msg.split('\n') }}"

- name: Based on machine brand and type
  debug:
    msg: "only when machine brand - type is ; Apple Inc. - MacBookAir4,2"
  when: |
    ansible_facts['system_vendor'] == "Apple Inc." and
    ansible_facts['product_name'] == "MacBookAir4,2"

- name: 0000-neofetch
  ansible.builtin.apt:
    pkg:
      - neofetch
      - lolcat
    update_cache: yes
    cache_valid_time: 3600
    state: present
