# Removing:
#   gnome-games - games for GNOME desktop
- name: apt-gnome-games
  ansible.builtin.apt:
    pkg:
      - gnome-games
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
    state: absent
