# - name: Print all available facts
#   ansible.builtin.debug:
#     var: ansible_facts

- name: Print machine brand, and OS details
  vars:
    machine_details: |
      OS system           : {{ ansible_facts['system'] }}
      OS distribution     : {{ ansible_facts['distribution_file_variety'] }} {{ ansible_facts['distribution_major_version'] }}.{{ ansible_facts['distribution_minor_version'] }} - {{ ansible_facts['distribution_release'] }}
      System vendor       : {{ ansible_facts['system_vendor'] }}
      Product name        : {{ ansible_facts['product_name'] }}
  debug:
    msg: "{{ machine_details.split('\n') }}"
