- name: Install NVIDIA legacy software
  ansible.builtin.apt:
    pkg:
      - nvidia-detect
      - linux-headers-amd64 
      - nvidia-legacy-390xx-driver
      - firmware-misc-nonfree 
      - nvidia-xconfig
    update_cache: yes
    cache_valid_time: 3600
    state: present
  when: |
    ansible_facts['system_vendor'] == "Dell Inc." and
    ansible_facts['product_name'] == "Lattitude E-6420" or
    ansible_facts['product_name'] == "Lattitude E-6430"
