- name: Set fn-keymode for Apple Inc. - MacBookAir4,2
  copy:
    dest: /etc/modprobe.d/hid_apple.conf
    content: | 
      options hid_apple fnmode=2
  when: |
    ansible_facts['system_vendor'] == "Apple Inc." and
    ansible_facts['product_name'] == "MacBookAir4,2"
  register: fn

- name: update initramfs for all kernels
  command: update-initramfs -u -k all
  when: |
    fn.changed and
    ansible_facts['system_vendor'] == "Apple Inc." and
    ansible_facts['product_name'] == "MacBookAir4,2"