- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: github-desktop
  community.general.flatpak:
    name: io.github.shiftey.Desktop
    state: present
    remote: flathub
